### ISSUE TITLE
Any Documentation

### ISSUE THREAD

**Issue by sm2x** [salimvanak/myWMS#1]
I know that such documentation exists on myWMS site but are there any changes on your version that needs documented?

**Comment by salimvanak** [comment]
I have started some documentation on the project wiki.  However, there is still a lot to complete.
As yet I have not made any functional changes to myWMS.  The only changes are a number of bug fixes and replacing the old desktop software based with a new java version. 

Are you planning on deploying myWMS.  I am happy to support you in the process if you think that will be helpful.

**Comment by sm2x** [comment]
Is it technically possible that postgresql can be replaced with mysql?

**Comment by salimvanak** [comment]
Running on MySQL (or MariaDB) should be no problem.  The ORM is hibernate and you would just use a different dialect in hibernate configuration.  myWMS can also be run on H2 although I don't trust it in a production environment with large datasets.  

There are some manual optimisations for Postgres we make.  They might need to be replicated in MySQL if you have a large dataset, again that should be no problem.

**Comment by sm2x** [comment]
I have noted that on your README, you have converted swing gui into javafx, im wondering if you know Open-Dolphin.org and how difficult to adapt OD on myWMS

**Comment by salimvanak** [comment]
I am not sure what advantage that would give you.  As I understanding it Open-Dolphin encapsulates business logic on the server side, there by separating it from the client side GUI.  This is exactly what the Wildfly services do in myWMS.   Apart from the initial set up, myWMS is basically set of functional transformations on the dataset (one could argue that myWMS is a server side only application).  

So the JavaFx rewrite was almost trivial,  the only business logic on the client side is controlling to user permissions and authorisation.  The JavaFx app just displays the current state of the data, and then calls the relevant service when the user requires.
